"""SUBCONSCIOUS.md content generation and injection."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .models import MemoryBlock


class SubconsciousInjector:
    """Generates and manages SUBCONSCIOUS.md content."""
    
    def __init__(self, agent_name: str = "Subconscious"):
        self.agent_name = agent_name
    
    def generate(
        self,
        memory_blocks: list[MemoryBlock],
        guidance_messages: list[str],
        agent_id: str | None = None,
        conversation_id: str | None = None,
        is_hosted: bool = True,
    ) -> str:
        """Generate SUBCONSCIOUS.md content."""
        lines = [
            "# Subconscious",
            "",
            "> This file is auto-generated by Kimi Subconscious. Do not edit manually.",
            "> It contains context from your Letta agent that persists across sessions.",
            "",
            "---",
            "",
        ]
        
        # Agent context
        lines.extend(self._format_context(agent_id, conversation_id, is_hosted))
        lines.append("")
        
        # Active guidance (most important - goes first)
        if guidance_messages:
            lines.extend(self._format_guidance(guidance_messages))
            lines.append("")
        
        # Memory blocks
        if memory_blocks:
            lines.extend(self._format_memory_blocks(memory_blocks))
            lines.append("")
        
        # Footer
        lines.extend([
            "---",
            "",
            f"*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
            "",
        ])
        
        return "\n".join(lines)
    
    def _format_context(
        self,
        agent_id: str | None,
        conversation_id: str | None,
        is_hosted: bool,
    ) -> list[str]:
        """Format the agent context section."""
        lines = ["## Context", ""]
        
        if is_hosted and agent_id:
            url = f"https://app.letta.com/agents/{agent_id}"
            if conversation_id:
                url += f"?conversation={conversation_id}"
            lines.append(f"**Agent:** [{self.agent_name}]({url})")
        elif agent_id:
            lines.append(f"**Agent:** {self.agent_name}")
            lines.append(f"**Agent ID:** `{agent_id}`")
            if conversation_id:
                lines.append(f"**Conversation ID:** `{conversation_id}`")
        else:
            lines.append(f"**Agent:** {self.agent_name}")
        
        lines.append("")
        lines.append(
            "This agent observes your Kimi Code sessions and maintains persistent memory "
            "across conversations. It learns your preferences, tracks project context, "
            "and provides guidance when relevant."
        )
        
        return lines
    
    def _format_guidance(self, messages: list[str]) -> list[str]:
        """Format guidance messages section."""
        lines = [
            "## Active Guidance",
            "",
            f"> Messages from your {self.agent_name} for this session:",
            "",
        ]
        
        for i, msg in enumerate(messages, 1):
            if len(messages) > 1:
                lines.append(f"### Message {i}")
                lines.append("")
            
            # Format the message
            formatted = msg.strip()
            lines.append(formatted)
            lines.append("")
        
        return lines
    
    def _format_memory_blocks(self, blocks: list[MemoryBlock]) -> list[str]:
        """Format memory blocks section."""
        lines = ["## Memory Blocks", ""]
        
        # Order blocks by importance
        priority_order = [
            "guidance",
            "user_preferences",
            "project_context",
            "pending_items",
            "session_patterns",
            "self_improvement",
            "core_directives",
            "tool_guidelines",
        ]
        
        # Sort blocks by priority
        block_map = {b.label: b for b in blocks}
        ordered_blocks = []
        
        for label in priority_order:
            if label in block_map:
                ordered_blocks.append(block_map[label])
        
        # Add any remaining blocks not in priority list
        for block in blocks:
            if block not in ordered_blocks:
                ordered_blocks.append(block)
        
        # Format each block
        for block in ordered_blocks:
            lines.extend(self._format_single_block(block))
            lines.append("")
        
        return lines
    
    def _format_single_block(self, block: MemoryBlock) -> list[str]:
        """Format a single memory block."""
        # Skip empty/default blocks in the output (but we might want to show them)
        value = block.value or ""
        if value.startswith("(") and "No " in value and value.endswith(")"):
            # Empty placeholder - show collapsed
            lines = [
                f"### {self._format_block_title(block.label)}",
                "",
                f"*{block.description}*",
                "",
                "*(Empty - will be populated as sessions accumulate)*",
            ]
        else:
            lines = [
                f"### {self._format_block_title(block.label)}",
                "",
                f"*{block.description}*",
                "",
                "```",
                value,
                "```",
            ]
        
        return lines
    
    def _format_block_title(self, label: str) -> str:
        """Convert snake_case to Title Case."""
        return label.replace("_", " ").title()
    
    def generate_minimal(self, guidance: str | None = None) -> str:
        """Generate minimal SUBCONSCIOUS.md for initial setup."""
        lines = [
            "# Subconscious",
            "",
            "> This file is auto-generated by Kimi Subconscious.",
            "",
            "---",
            "",
        ]
        
        if guidance:
            lines.extend([
                "## Active Guidance",
                "",
                guidance,
                "",
                "---",
                "",
            ])
        else:
            lines.extend([
                "## Setup Required",
                "",
                "Run `kimisub setup` to configure your Subconscious agent.",
                "",
                "---",
                "",
            ])
        
        lines.append(f"*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        lines.append("")
        
        return "\n".join(lines)
    
    def update_guidance(
        self,
        existing_content: str,
        new_guidance: list[str],
    ) -> str:
        """Update just the guidance section of existing content."""
        # Split into sections
        lines = existing_content.split("\n")
        
        # Find the guidance section
        guidance_start = None
        guidance_end = None
        
        for i, line in enumerate(lines):
            if line.strip() == "## Active Guidance":
                guidance_start = i
            elif guidance_start is not None and line.strip().startswith("## "):
                guidance_end = i
                break
        
        if guidance_start is None:
            # No guidance section - add after context
            for i, line in enumerate(lines):
                if line.strip() == "## Context":
                    # Find end of context section
                    for j in range(i + 1, len(lines)):
                        if lines[j].strip().startswith("## "):
                            guidance_start = j
                            break
                    break
        
        # Generate new guidance section
        new_section = self._format_guidance(new_guidance)
        
        if guidance_start is not None and guidance_end is not None:
            # Replace existing guidance
            new_lines = lines[:guidance_start] + new_section + lines[guidance_end:]
        elif guidance_start is not None:
            # Insert before guidance_start
            new_lines = lines[:guidance_start] + new_section + [""] + lines[guidance_start:]
        else:
            # Append to end (before footer)
            # Find footer
            footer_start = None
            for i, line in enumerate(lines):
                if line.strip() == "---" and i > 5:
                    footer_start = i
                    break
            
            if footer_start:
                new_lines = lines[:footer_start] + [""] + new_section + lines[footer_start:]
            else:
                new_lines = lines + [""] + new_section
        
        # Update timestamp
        result = "\n".join(new_lines)
        result = self._update_timestamp(result)
        
        return result
    
    def _update_timestamp(self, content: str) -> str:
        """Update the last updated timestamp."""
        lines = content.split("\n")
        new_lines = []
        
        for line in lines:
            if line.startswith("*Last updated:"):
                new_lines.append(f"*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
            else:
                new_lines.append(line)
        
        return "\n".join(new_lines)
